title: Ludvig Janiuk's blog
author: Ludvig Janiuk
description: "To subscribe: email ludvig dot janiuk at proton dot me. Sharing experiences and thoughts on various topics mostly related to climate change or software engineering. I work as a JVM Sustaining Engineer at Oracle, but my opinions are my own."
theme: minima
header_pages:
  - polski.md
  - svenska.md
  - english.md
  - about.md
