title: Ludvig Janiuk's blog
author: Ludvig Janiuk
description: "I work full-time on responding to the climate crisis. On this blog I share my thougts and experiences. To subscribe: email ludvig dot janiuk at proton dot me."
theme: minima
header_pages:
  - polski.md
  - svenska.md
  - english.md
  - about.md
